import {
  Box,
  Flex,
  Image,
  Text,
  InputGroup,
  Input,
  VStack,
  HStack,
  Icon,
  SimpleGrid,
} from "@chakra-ui/react";
import React from "react";

import { MotionButton, MotionFlex } from "../../../constants/components/motion";
import { chakra } from "@chakra-ui/react";

import { startUpStore } from "../../../store/start_up";
import { useState, useEffect } from "react";

import { useWindowSize } from "../../../custom_hooks";

import {
  ServicesContainerPlain,
  ServicesContainer,
} from "../../../constants/components/utilities";

import "@fontsource/poppins";
export default function Home() {
  const setshowStartup = startUpStore((state) => state.set_show_startup);

  useEffect(() => {
    setshowStartup(false);
  });
  const { height, width } = useWindowSize();

  function CallToAction() {
    return (
      <Flex
        flexDir={["row", "row", "row", "row", "row", "row"]}
        w={width}
        alignItems={["end", "end", "end", "end", "end", "end"]}
        pt={["8em", "8em", "8em", "8em", "10em", "10em"]}
        pb={["8em", "8em", "8em", "8em", "6em", "10em"]}
        px={["7%", "7%", "7%", "7%", "10%", "10%"]}
      >
        <Box
          borderRadius={"1.5em"}
          height={["300px", "450px", "450px", "450px", "300px", "400px"]}
          w={"full"}
          style={{
            overflow: "hidden",
          }}
          filter={"auto"}
          brightness={"30%"}
        >
          <Image
            src={
              "https://images.unsplash.com/photo-1587620962725-abab7fe55159?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1631&q=80"
            }
            alt="ms"
            objectFit={"cover"}
            boxSize={"full"}
          />
        </Box>
        <VStack
          alignItems={"start"}
          spacing={"5px"}
          position={"absolute"}
          mb={["30px", "60px", "60px", "60px", "40px", "60px"]}
          ml={["20px", "50px", "50px", "50px", "50px", "50px"]}
        >
          <Box w={["13%", "25%", "25%", "25%", "8%", "10%"]}>
            <Image src={"/technical.svg"} alt="ms" boxSize={"full"} />
          </Box>
          <VStack alignItems={"start"} spacing={"15px"}>
            <VStack
              alignItems={"start"}
              spacing={["-5px", "-10px", "-10px", "-10px", "-10px", "-10px"]}
            >
              <chakra.h3
                fontFamily={"Poppins.black"}
                fontSize={["25px", "30px", "30px", "30px", "30px", "35px"]}
                fontWeight="black"
                letterSpacing={{
                  base: "normal",
                  md: "normal",
                }}
                color="#D74848"
                whiteSpace={["normal", "normal", "pre-line", "pre-line"]}
              >
                Technical
              </chakra.h3>
              <chakra.h3
                fontFamily={"Poppins.black"}
                fontSize={["15px", "20px", "20px", "20px", "20px", "21px"]}
                fontWeight="thin"
                letterSpacing={{
                  base: "normal",
                  md: "normal",
                }}
                color="#FFFFFF"
                whiteSpace={["normal", "normal", "pre-line", "pre-line"]}
              >
                More efficiency
              </chakra.h3>
            </VStack>
            <chakra.p
              fontSize={["10px", "14px", "15px", "15px", "13px", "15px"]}
              color="white"
              maxW={["280px", "500px", "500px", "500px", "500px"]}
              whiteSpace={["normal", "normal", "pre-line", "pre-line"]}
              fontFamily={"Poppins"}
            >
              Systems ensure that maximum work is getting done with minimal
              effort and time. We offer support, advice and development
              solutions.
            </chakra.p>
          </VStack>
        </VStack>
      </Flex>
    );
    sa;
  }

  function TypeOfServices() {
    const dummyData = [
      {
        title: "ONLINE AVAILABILITY",
        icon: "/globe.svg",
        subTitle: "Web Development",

        description:
          "Websites, webshops or other online platforms. We offer custom-made solutions and build with different technologies, in various styles and for all type of organizations.",
      },
      {
        title: "SMARTPHONE TOOLS",
        icon: "/mobile.svg",
        subTitle: "Mobile Apps",

        description:
          "Nowadays, most online traffic is generated by smartphones, which makes it increasingly attractive to have a Mobile App developed for your customers and other types of users .",
      },
      {
        title: "TRUSTED ENVIROMENT",
        icon: "/cloud.svg",
        subTitle: "Hosting Service",

        description:
          "Being always online has become more critical than ever before. Security, performance, and scalability are recurring topics we respond too. Let us inform and advise you about the best solutions.",
      },
      {
        title: "LOGICAL DESIGN",
        icon: "/sitemap.svg",
        subTitle: "Infrastructure Management",

        description:
          "Smart IT design ensures efficient progress within the infrastructure. Also, this offers a clear overview, so problems in the network are recognized earlier and getting solved faster.",
      },
      {
        title: "PROCESS OPTIMIZATION",
        icon: "/technical.svg",
        subTitle: "Digital Automization",

        description:
          "Automating processes and activities saves time and energy, which leaves more work capacity for crucial matters within the organization. External or self-developed systems help you achieve this.",
      },
      {
        title: "R&D",
        icon: "/atom.svg",
        subTitle: "Research and development",

        description:
          "Unfortunately, not in the market is suitable for your business, which means that your product or service needs to be developed. We help you achieve anything. But first, we need to know what you are looking for.",
      },
    ];

    return (
      <Flex
        flexDir={["column", "column", "row", "row", "row", "row"]}
        pb={"200px"}
      >
        <VStack alignItems={"start"} spacing={"55px"} width={"100%"} px={"10%"}>
          <Flex
            dir="row"
            justifyContent={["center", "center", "flex-start", "flex-start"]}
          >
            <chakra.h3
              fontFamily={"Poppins.black"}
              paddingY={["30px", "30px", "30px", "30px", "23px", "20px"]}
              fontSize={["30px", "40px", "40px", "40px", "40px", "50px"]}
              fontWeight="black"
              letterSpacing={{
                base: "normal",
                md: "normal",
              }}
              color="#111518"
              whiteSpace={["normal", "normal", "pre-line", "pre-line"]}
            >
              {`Type of services`}
            </chakra.h3>
          </Flex>

          <SimpleGrid
            alignItems={"start"}
            alignSelf={"start"}
            justifyItems={"start"}
            spacingX={"150px"}
            spacingY={"100px"}
            columns={[1, 1, 1, 1, 3, 3]}
          >
            {dummyData.map((entry, index) => (
              <ServicesContainerPlain data={dummyData} dataIndex={index} />
            ))}
          </SimpleGrid>
        </VStack>
      </Flex>
    );
  }

  function OurService() {
    const dummyData = [
      {
        title: "Commercial",
        icon: "/commercial.svg",
        routeURL: "/services/commercial",
        subTitle: "More revenue",

        description:
          "We optimize your Sales and Marketing processes and aim to increase your reach and inbound/ outbound traffic of potential business",
      },
      {
        title: "Creative",
        icon: "/creative.svg",
        routeURL: "/services/creative",

        subTitle: "More appeal",

        description:
          "In most cases, a collaboration is started based on the first impression. That’s why creative design is so important. To stand out visually.",
      },
    ];
    return (
      <Flex
        flexDir={["column", "column", "row", "row", "row", "row"]}
        pb={"100px"}
      >
        <VStack alignItems={"start"} spacing={"55px"} width={"100%"} px={"10%"}>
          <Flex
            dir="row"
            justifyContent={["center", "center", "flex-start", "flex-start"]}
          >
            <chakra.h3
              fontFamily={"Poppins.black"}
              paddingTop={["30px", "30px", "30px", "30px", "23px", "15px"]}
              fontSize={["30px", "40px", "40px", "40px", "40px", "50px"]}
              fontWeight="black"
              letterSpacing={{
                base: "normal",
                md: "normal",
              }}
              color="#111518"
              whiteSpace={["normal", "normal", "pre-line", "pre-line"]}
            >
              {`Other Services`}
            </chakra.h3>
          </Flex>

          <SimpleGrid
            alignItems={"start"}
            alignSelf={"start"}
            justifyItems={"start"}
            spacingX={"80px"}
            spacingY={"50px"}
            columns={[1, 1, 1, 1, 3, 3]}
          >
            {dummyData.map((entry, index) => (
              <ServicesContainer data={dummyData} dataIndex={index} />
            ))}
          </SimpleGrid>
        </VStack>
      </Flex>
    );
  }

  return (
    <MotionFlex
      initial={{ opacity: 0 }}
      animate={{ opacity: 100, delay: 1 }}
      transition={{ ease: "easeIn", duration: 10, delay: 1 }}
    >
      <Box bgColor={"#F3F8FF"}>
        <CallToAction />
        <TypeOfServices />
        <OurService />
      </Box>
    </MotionFlex>
  );
}
